### ISSUE TITLE
ssl certificate issue for localhost (127.0.0.1)

### ISSUE THREAD

**Issue by hackrat** [goshippo/shippo-php-client#1]
I have tried this api library for php on localhost but getting below metioned error.

Fatal error: Uncaught exception 'Shippo_ApiConnectionError' with message 'Unexpected error communicating with Shippo. If this problem persists, let us know by contacting us through our contact form. (Network error [errno 77]: error setting certificate verify locations: CAfile: /opt/lampp/htdocs/magento/shippo/lib/Shippo/../cacert.pem CApath: none )' in /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiRequestor.php:282 Stack trace: #0 /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiRequestor.php(250): Shippo_ApiRequestor->handleCurlError(77, 'error setting c...') #1 /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiRequestor.php(176): Shippo_ApiRequestor->_curlRequest('post', 'https://api.gos...', Array, Array) #2 /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiRequestor.php(101): Shippo_ApiRequestor->_requestRaw('post', '/v1/customs/dec...', Array) #3 /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiResource.php(107): Shippo_ApiRequestor->request('post', '/v1/customs/dec...', Array) #4 /opt/lampp/htdocs/magento/shippo/lib/Sh in /opt/lampp/htdocs/magento/shippo/lib/Shippo/ApiRequestor.php on line 282

**Comment by pennadl** [comment]
for localhost, a bruteforce workaround could be edit ApiRequestor.php and add these two lines
```
$curlOptions[CURLOPT_SSL_VERIFYHOST] = FALSE; 
$curlOptions[CURLOPT_SSL_VERIFYPEER] = FALSE;
```

after 

`$curlOptions[CURLOPT_FOLLOWLOCATION] = TRUE;`

this will avoid to check for a valid certificate

**Comment by gplcart** [comment]
Things changed in 1.3.2
Add 
```
$curlOptions[CURLOPT_SSL_VERIFYHOST] = false; 
$curlOptions[CURLOPT_SSL_VERIFYPEER] = false;
```

before 

`curl_setopt_array($curl, $curlOptions);`

in CurlClient.php. Its around line 45

So bad we have to do it manually. Why not to disable the verifier automatically on test token?

**Comment by francois-g** [comment]
Another way around this issue is to download the [cacert.pem hosted by curl](https://curl.haxx.se/docs/caextract.html) and put it in `lib` directory where `Shippo.php` is located.

I have the problem on a Windows 7 computer.

**Comment by gplcart** [comment]
@francois-g Better yet, thanks.

**Comment by Bit-Coin** [comment]
`\Shippo\Shippo\CurlClient.php`
go to line `44` and add these lines: 
```
        $curlOptions[CURLOPT_SSL_VERIFYPEER] = false;
        $curlOptions[CURLOPT_SSL_VERIFYHOST] = false;
```
