### ISSUE TITLE
Address is_residential expects real boolean

### ISSUE THREAD

**Issue by nmatthews333** [goshippo/shippo-php-client#16]
shippo-php-client/lib/Shippo/ApiRequestor.php > _encodeObjects()

boolean convert to string returns this error when passing in an address with 'is_residential' set to Shippo_Shipment::create():

_{"address_to": [{"residential": ["'true' value must be either None, True or False."]}]}_

Api expects boolean

**Comment by assislucas** [comment]
Hi nmatthews333, thanks for letting us know about this. We've identified the issue and will update the code soon to fix it.

**Comment by ThiagoRRamos** [comment]
Fixed the issue on Pull Request #17 . It should be working now.
