### ISSUE TITLE
Shippo_CarrierAccount::all filter not working when using carrier => dhl_express

### ISSUE THREAD

**Issue by claw68** [goshippo/shippo-php-client#18]
This code returns all my carriers including usps, parcelforce and both dhl_express accounts

`Shippo_CarrierAccount::all()`

These filters returns the expected result:

`Shippo_CarrierAccount::all(array('carrier'=> 'usps'));`
`Shippo_CarrierAccount::all(array('carrier'=> 'parcelforce'));`

While this one returns 0 rows

`Shippo_CarrierAccount::all(array('carrier'=> 'dhl_express'));`

**Comment by simonkreuz** [comment]
@claw68 - we'll look into both issues you've opened and will get back to you soon.

**Comment by ThiagoRRamos** [comment]
Hey, @claw68 . Thank you for reporting this issue. We identified the problem and will resolve it soon.

**Comment by claw68** [comment]
Thanks!

**Comment by sbeidas** [comment]
This issue has been fixed. Thank you for pointing it out :)
