### ISSUE TITLE
CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by cturner80** [goshippo/shippo-php-client#21]
Line 232 of ApiRequestor.php has the following:

```
$curlOptions[CURLOPT_FOLLOWLOCATION] = TRUE;
```

This setting cannot be used in conjunction with open_basedir, which is enabled on some servers for security reasons.

I set this to FALSE and things seemed to work fine with limited testing. Is there any reason this is needed?

**Comment by sbeidas** [comment]
@cturner80 Thank you for pointing this out :)

I have removed this option and CURLOPT_FOLLOWLOCATION now defaults to False. 

Thanks again!
