### ISSUE TITLE
How can i get available Parcel Templates

### ISSUE THREAD

**Issue by korcstar** [goshippo/shippo-php-client#28]
I want to get available parcel template by api
is there any solution?

**Comment by simonkreuz** [comment]
We currently don't provide an endpoint to retrieve a list of parcel templates. We recommend storing a list of all applicable templates locally. You can find all available templates by carrier here https://goshippo.com/docs/reference#parcel-templates. Those values hardly ever change - typically the carriers update them once a year, if at all.
