### ISSUE TITLE
where to use sync=True when purchasing a label

### ISSUE THREAD

**Issue by pennadl** [goshippo/shippo-php-client#4]
Hello,

It's not clear where sync=True should be used when purchasing a label.

This is your code example
```
//Purchase the desired rate. sync=True indicates that the function will wait until the 
//carrier returns a shipping label before it returns
$transaction = Shippo_Transaction::create(array('rate'=> $rate["object_id"]));
```

so, should it be used in this way? `$transaction = Shippo_Transaction::create(array('rate'=> $rate["object_id"], 'sync' => true));`

Thanks

**Comment by sbeidas** [comment]
Sorry for the confusion, the sync option has been removed from Example.php as it is something we do not support in the PHP client. We are investigating several options that could help us make this possible.
