### ISSUE TITLE
The autoloader expected class "Shippo" to be defined in file

### ISSUE THREAD

**Issue by maykino** [goshippo/shippo-php-client#46]
What happened in the newest version? I get the following error:

  [RuntimeException]
  The autoloader expected class "Shippo" to be defined in file "/var/www/vendor/composer/../shippo/shippo-php/lib/Shippo/Shippo.php". The file was found but the class was not in it, the class name or namespace p
  robably has a typo.

**Comment by zackkrida** [comment]
Yeah looks like something went wrong with the attempt to namespace in 1.3.1

 `Class 'Shippo' not found`

**Comment by mootrichard** [comment]
Yeah it looks like you're right, we are planning on rolling back the most recent changes and revisiting doing the namespacing.

**Comment by markh28** [comment]
This seems to be keeping my woocommerce plugin from working correctly.  Is there an old version I can download and use?

**Comment by maykino** [comment]
1.3.0 works for me fine

**Comment by markh28** [comment]
Where can I get 1.3.0?

**Comment by mootrichard** [comment]
We are currently rolling it back with #48. Just waiting for our CI builds to clear before merging.

Once that is merged, it should be back to how it was before we had tried implementing namespacing.

**Comment by mootrichard** [comment]
Closing issue, as this has been resolved with the merge of #48
