### ISSUE TITLE
Please retract version 1.3.1 because breaking changes!

### ISSUE THREAD

**Issue by casperbakker** [goshippo/shippo-php-client#47]
Thanks for adding namespace support 👍  But...

You added it in 1.3.1, which is totally against best-practices. Because this is a breaking change, it should be reflected in the version number. Especially since you suggest in the readme to add this package with Composer as version '1.*'

So everyone that added this package in the recommended way and does a `composer update`, has a completely broken product.

I would advice to retract version 1.3.1, and add a new 2.0.0 version with namespacing support.

**Comment by rosshettel** [comment]
Agreed, this definitely should be rolled back because it's broken, but this really wasn't a *.*.1 release at all, at least if you're following semantic versioning.

**Comment by mootrichard** [comment]
We are in the process of rolling this back with #48. Just fixing some issues with our CI since Travis changed their support for HHVM. 

Once that change has been merged, it should be back to how it was.

**Comment by mootrichard** [comment]
Closing issue, as its been resolved by #48.
