### ISSUE TITLE
Version not changing

### ISSUE THREAD

**Issue by sumannaresh02** [goshippo/shippo-php-client#51]
Hello,

I want to use Shippo's old API "2016-10-25". so I set the version using "\Shippo::setApiVersion('2016-10-25');". but version not changing. 

How to i change the version of API using Code.

**Comment by mootrichard** [comment]
Although you've already closed this, you can't really set the API version using the wrapper. Your API version is automatically set at the API level. You can find more info about versioning [here](https://goshippo.com/docs/changelog).

Also, if you set it in the headers, you could use a future version of the API by adding in that version in the header as its indicated [here](https://goshippo.com/docs/versioning).
