### ISSUE TITLE
Installing Shippo PHP Manually

### ISSUE THREAD

**Issue by jligda** [goshippo/shippo-php-client#52]
Is there a way to install the Shippo PHP files manually without Composer or Laravel?  I uploaded the files manually, but I get an error when I run the examples: Warning: require_once(/var/www/html/shippo/examples../../vendor/autoload.php): failed to open stream: No such file or directory.  I'm not familiar with Composer or Laravel and have not been able to get Composer to work.

**Comment by jligda** [comment]
I asked this on Stackoverflow as well: https://stackoverflow.com/questions/44160149/installing-shippo-php-manually

**Comment by mootrichard** [comment]
I left a comment for you on SO, but was curious where you've installed Shippo and where/how you're trying to require it. Within the `lib` folder, you can find the `Shippo.php` file that you can require to import all of the other functionality of the PHP client library.

**Comment by jligda** [comment]
Thanks.  OK I see in the example files it says:

require_once(__DIR__ . '../../vendor/autoload.php');

// or if you do not have or want the composer autoload feature do
// require_once('path/to/shippo/library/folder/' . 'lib/Shippo.php');

So it looks like all that I need to do is comment out the autoload and
uncomment the lib/Shippo.php:

//require_once(__DIR__ . '../../vendor/autoload.php');
// or if you do not have or want the composer autoload feature do

require_once('path/to/shippo/library/folder/' . 'lib/Shippo.php¹);

I¹ll give it a try

Jay Ligda

From:  Richard Moot <notifications@github.com>
Reply-To:  goshippo/shippo-php-client
<reply+005eb795e5f54284c6f23e3303034bfd5d25c9dc3763389292cf00000001153d8f9f9
2a169ce0dc355cd@reply.github.com>
Date:  Wednesday, May 24, 2017 at 11:14 AM
To:  goshippo/shippo-php-client <shippo-php-client@noreply.github.com>
Cc:  Jay Ligda <jligda@steadyserve.net>, Author <author@noreply.github.com>
Subject:  Re: [goshippo/shippo-php-client] Installing Shippo PHP Manually
(#52)

**Comment by jligda** [comment]
Richard, thanks.  I tried the code below.  More specifically:

 require_once($_SERVER['DOCUMENT_ROOT'].'/shippo/lib/Shippo.php¹);

Used our test key.  Now I get:

Fatal error: Uncaught exception 'Exception' with message 'Shippo needs the
Multibyte String PHP extension.' in /var/www/html/shippo/lib/Shippo.php:11
Stack trace: #0 /var/www/html/shippo/examples/track-shipment.php(42):
require_once() #1 {main} thrown in /var/www/html/shippo/lib/Shippo.php on
line 11

I tried installing mbstring:

yum install php-mbstring

service httpd restart


No avail.  If you have any insight, please let me know.

Thanks!

Jay Ligda


From:  Jay Ligda <jligda@steadyserve.net>
Date:  Wednesday, May 24, 2017 at 11:54 AM
To:  goshippo/shippo-php-client
<reply+005eb795e5f54284c6f23e3303034bfd5d25c9dc3763389292cf00000001153d8f9f9
2a169ce0dc355cd@reply.github.com>
Subject:  Re: [goshippo/shippo-php-client] Installing Shippo PHP Manually
(#52)

**Comment by mootrichard** [comment]
That is a non-default extension for PHP. You can find more info on installing it here: [http://www.php.net/manual/en/mbstring.installation.php](http://www.php.net/manual/en/mbstring.installation.php)

**Comment by jligda** [comment]
No such luck getting that installed.  Thanks for the help anyway.  It wound
up crashing my dev environment when I tried to install the extensions.
Rebuilding now.  I¹ll try again.

From:  Richard Moot <notifications@github.com>
Reply-To:  goshippo/shippo-php-client
<reply+005eb795ff69b1dd4059bb09e74241436f367a66299da19792cf00000001153da5779
2a169ce0dc355cd@reply.github.com>
Date:  Wednesday, May 24, 2017 at 12:48 PM
To:  goshippo/shippo-php-client <shippo-php-client@noreply.github.com>
Cc:  Jay Ligda <jligda@steadyserve.net>, Author <author@noreply.github.com>
Subject:  Re: [goshippo/shippo-php-client] Installing Shippo PHP Manually
(#52)

**Comment by mootrichard** [comment]
I would highly recommend revisiting using Composer. Its in a lot of various PHP projects for managing dependencies and really simplifies installing and requiring third-party libraries for your projects.

**Comment by jligda** [comment]
Yes, I have run into it quite a bit lately.  I¹ll see if I can figure it
out.  I¹m on the Composer website looking through instructions.

Thank you!

From:  Richard Moot <notifications@github.com>
Reply-To:  goshippo/shippo-php-client
<reply+005eb795e155beebb095c7683105f716b6ae05b44e78dcbe92cf00000001153dd8029
2a169ce0dc355cd@reply.github.com>
Date:  Wednesday, May 24, 2017 at 4:23 PM
To:  goshippo/shippo-php-client <shippo-php-client@noreply.github.com>
Cc:  Jay Ligda <jligda@steadyserve.net>, Author <author@noreply.github.com>
Subject:  Re: [goshippo/shippo-php-client] Installing Shippo PHP Manually
(#52)

**Comment by jligda** [comment]
Richard,

You have me sold on Composer.  I have my dev environment back up and running
and I think I installed Composer on it.  Will you walk me through the
process of installing Shippo with it?  I see the instructions here:
https://github.com/goshippo/shippo-php-client

The steps say to:

"Create/append the following to your composer.json file²

I do not know where the composer.json file is.

Then it says:
Install via:
  composer.phar install
I do not know where to run this command.

Also, do you know anything about AWS Elastic Beanstalk and if I will need to
install Composer and Shippo on my AWS Beanstalk instance when I deploy my
development files to Beanstalk?  Has anyone asked about that before?  I have
a support ticket in to AWS about this, but wants to know if it has come up
with Shippo support at all.  Usually when I deploy my site to Beanstalk, I
just zip up the website files and upload them, but if there are server
configuration changes, these changes will also need to be made on the
Beanstalk instance.

Thanks!

Jay Ligda


From:  Richard Moot <notifications@github.com>
Reply-To:  goshippo/shippo-php-client
<reply+005eb795e155beebb095c7683105f716b6ae05b44e78dcbe92cf00000001153dd8029
2a169ce0dc355cd@reply.github.com>
Date:  Wednesday, May 24, 2017 at 4:23 PM
To:  goshippo/shippo-php-client <shippo-php-client@noreply.github.com>
Cc:  Jay Ligda <jligda@steadyserve.net>, Author <author@noreply.github.com>
Subject:  Re: [goshippo/shippo-php-client] Installing Shippo PHP Manually
(#52)

**Comment by mootrichard** [comment]
@jligda I can answer a few of your questions here, but I am going to be closing this out, since this issue is outside of the scope of this project.

I highly recommend reading through the Composer docs to get familiar with how they work and how to utilize them for your own project. [https://getcomposer.org/doc/03-cli.md#init](https://getcomposer.org/doc/03-cli.md#init)

The reason you can't find a `composer.json` file, is you likely haven't created one in your project yet. Once you do, you can just add Shippo in the way described in our `README.md`.

Giving any advice on AWS Elastic Beanstalk should be directed over to AWS. I'd love to give you advice on that, but that seriously digresses to resolving any Shippo PHP Library related concerns. 

There should be a sufficient amount of tutorials out there that could better guide you on how to setup your application on your chosen cloud platform provider.
