### ISSUE TITLE
Create Shipment with Multiple Parcels not working

### ISSUE THREAD

**Issue by marwankhanfar** [goshippo/shippo-php-client#73]
the following request works if you have one parcel only if multiple parcels added it returns nothing

curl https://api.goshippo.com/shipments/  \
    -H "Authorization: ShippoToken shippo_test_*********************" \
    -H "Content-Type: application/json"  \
    -d '{
            "address_from": {
                "name": "Mr. Hippo",
                "street1": "215 Clayton St.",
                "city": "San Francisco",
                "state": "CA",
                "zip": "94117",
                "country": "US",
                "phone": "+1 555 341 9393",
                "email": "support@goshippo.com"
            },
            "address_to": {
                "name": "Mrs. Hippo",
                "street1": "965 Mission St.",
                "city": "San Francisco",
                "state": "CA",
                "zip": "94105",
                "country": "US",
                "phone": "+1 555 341 9393",
                "email": "support@goshippo.com"
            },
            "parcels": [
                {
                    "length": "5",
                    "width": "5",
                    "height": "5",
                    "distance_unit": "in",
                    "weight": "2",
                    "mass_unit": "lb"
                },
                {
                    "length": "10",
                    "width": "10",
                    "height": "10",
                    "distance_unit": "in",
                    "weight": "2",
                    "mass_unit": "lb"
                }
            ],
            "async": false
        }'

**Comment by josephmancuso** [comment]
@marwankhanfar multiple parcels are not supported when using a test token. using a live token will allow you to see rates for multiple parcels

**Comment by Steco17** [comment]
Hello i have the same issue here i even changed my token to live but nothing. i added carriers as suggested in goshippo documentation but still nothing. but when i use a parcel everything is fine. can anyone help[ please

**Comment by josephmancuso** [comment]
@Steco17 you need to specify a parcel. Can you post your request here?

**Comment by marwankhanfar** [comment]
@josephmancuso your answer is incorrect, turned out multi-piece shipping is not available for all carriers, I was able to get rates for FedEx on sandbox but not ups 

https://goshippo.com/docs/multipiece/
